apiVersion: v1
kind: Service
metadata:
  name: nv-nodeport-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"nv-backend-config"}}'
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: uplifted-agency-369506
  type: NodePort
